import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar bg-background">
          <div className="flex-1">
            <a className="btn btn-ghost text-xl">3pi4</a>
          </div>
          <div className="flex-none">
            <ul className="menu menu-horizontal px-1">
              <li>
                <a>Portfolio</a>
              </li>
              <li>
                <details>
                  <summary>Contact me</summary>
                  <ul className="bg-background rounded-t-none p-2">
                    <li>
                      <a>LinkedIn</a>
                    </li>
                    <li>
                      <a>Email</a>
                    </li>
                    <li>
                      <a>Fiver</a>
                    </li>
                  </ul>
                </details>
              </li>
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
